name: jhubk8s
channels:
  - conda-forge
dependencies:
- python=3.5
- sphinx>=1.3.6,!=1.5.4
- pip:
    - recommonmark==0.4.0
    - ruamel.yaml<0.15
    - git+git://github.com/choldgraf/sphinx-jsonschema.git@jsonpointer
